### ISSUE TITLE
Text Edit

### ISSUE THREAD

**Issue by NyanekoNNK** [DiamondCoder02/nsfw-game-manager#11]
either make the text uneditable and click to copy or make it actually save your edits......
![image](https://github.com/DiamondCoder02/nsfw-game-manager/assets/130905090/8759c652-c4f6-4437-8830-33e38b09abc4)

**Comment by DiamondCoder02** [comment]
fixed in 7dfb4e9817acfd3a00016a97845875fd7e3bbce6
