### ISSUE TITLE
Welcome popup

### ISSUE THREAD

**Issue by NyanekoNNK** [DiamondCoder02/nsfw-game-manager#13]
A popup the first time you start the program
put it in the Other tab welcome button too!

Message:
Welcome to your very own hentai database :3

The program is very simple and easy to use but you might want to check the wiki for the first time you use it because it lists every important feature / info about the program.
(Link)

The program works but still in the early access stage so we try to improve it consistently with feedbacks from all of you.

If you encounter an issue please provide feedback here: (link)

Have fun :3

**Comment by DiamondCoder02** [comment]
Done af601cba1ecfb4513e261c501c236151849886af
