### ISSUE TITLE
Credits and FAQ is white in dark mode

### ISSUE THREAD

**Issue by NyanekoNNK** [DiamondCoder02/nsfw-game-manager#8]
Fix this pls.
![image](https://github.com/DiamondCoder02/nsfw-game-manager/assets/130905090/2c7df6f2-81f5-4bb6-8d75-2fb28b5c0251)

**Comment by DiamondCoder02** [comment]
Fixed in:
https://github.com/DiamondCoder02/nsfw-game-manager/commit/d772b0677b6d950881423849430f49e99fa01a44
