### ISSUE TITLE
Update game button buggy

### ISSUE THREAD

**Issue by NyanekoNNK** [DiamondCoder02/nsfw-game-manager#9]
Why last 2 is switched in update game?
![image](https://github.com/DiamondCoder02/nsfw-game-manager/assets/130905090/839cfbe2-8d04-4882-aab4-47678c03c35e)

Also, align the text to the right side and add like 2 tabs or idk...... so its easier to read
![image](https://github.com/DiamondCoder02/nsfw-game-manager/assets/130905090/aa5a68e7-40f7-490e-bd52-337f6d36ca60)

Also also, if you cancel to update game it gives both updated and not updated window at the same time

ALSO rename API refresh and Refresh Table because its really confusing

**Comment by DiamondCoder02** [comment]
- [ ] Last 2 switch placed -> will be fixed
- [ ] Aligning
- [x] cancel shows 2 dialog -> fixed
- [ ] renaming
